#!/usr/bin/env pwsh
# Installs the QRSPI GitHub Copilot kit into user scope (~/.copilot). Merges:
# overwrites same-named files, leaves your other files alone. Re-run any time
# you change something in this repo.
#
# Claude Code is delivered as a PLUGIN, not by this script — add the marketplace
# (lotea-be/ai-agent-marketplace) and run `/plugin install qrspi@lotea-agents`.
# This script installs only the GitHub Copilot artifacts (Copilot cannot consume
# a Claude Code plugin).
#
# Usage:
#   ./install.ps1                 # install Copilot kit + offer VS Code settings
#   ./install.ps1 -SkipSettings   # don't touch VS Code settings.json
#
# claude/ is the source of truth. copilot/ is generated from it by
# /qrspi-sync-copilot (run that after editing claude/, then commit copilot/).

param(
    # Skip the VS Code settings.json patch prompt (for non-interactive / CI runs).
    [switch]$SkipSettings
)

$ErrorActionPreference = 'Stop'
$src = $PSScriptRoot

function Copy-Tree($from, $to, $label) {
    if (-not (Test-Path $from)) { Write-Warning "missing source: $from"; return }
    New-Item -ItemType Directory -Force $to | Out-Null
    Copy-Item (Join-Path $from '*') $to -Recurse -Force
    $n = (Get-ChildItem $from -Recurse -File).Count
    Write-Host ("  {0,-22} {1} file(s)" -f $label, $n) -ForegroundColor Green
}

# Candidate VS Code user-settings.json paths for this OS (stable, Insiders, VSCodium).
function Get-VSCodeSettingsPaths {
    if ($IsWindows -or $env:OS -eq 'Windows_NT') { $base = $env:APPDATA }
    elseif ($IsMacOS)                            { $base = Join-Path $HOME 'Library/Application Support' }
    else                                         { $base = Join-Path $HOME '.config' }
    'Code', 'Code - Insiders', 'VSCodium' |
        ForEach-Object { Join-Path $base (Join-Path $_ 'User/settings.json') }
}

# Offer to add the three chat.*FilesLocations entries that point VS Code at ~/.copilot.
# Edits text (not a JSON round-trip) so comments/trailing commas in settings.json survive.
function Add-CopilotSettings($settingsPath) {
    $entries = [ordered]@{
        'chat.promptFilesLocations'       = '~/.copilot/prompts'
        'chat.agentFilesLocations'        = '~/.copilot/agents'
        'chat.instructionsFilesLocations' = '~/.copilot/instructions'
    }

    $exists = Test-Path $settingsPath
    $text   = if ($exists) { Get-Content -Raw -LiteralPath $settingsPath } else { "{`n}`n" }

    $toInject = @()
    foreach ($key in $entries.Keys) {
        $path = $entries[$key]
        if ($text -match [regex]::Escape($path)) {
            Write-Host "    ok (already set)  $key" -ForegroundColor DarkGray
        }
        elseif ($text -match [regex]::Escape('"' + $key + '"')) {
            Write-Warning "    $key exists but lacks $path — add `"$path`": true to it by hand."
        }
        else {
            $toInject += '    "{0}": {{ "{1}": true }},' -f $key, $path
        }
    }
    if (-not $toInject) { Write-Host "  VS Code settings already wired for ~/.copilot." -ForegroundColor Green; return }

    Write-Host "`n  Add to $settingsPath :" -ForegroundColor Cyan
    $toInject | ForEach-Object { Write-Host "  $_" -ForegroundColor Yellow }
    $ans = Read-Host "  Patch settings.json now? (y/N)"
    if ($ans -notmatch '^(y|yes)$') { Write-Host "  Skipped — add the lines above by hand to enable the prompts." -ForegroundColor DarkCyan; return }

    $brace = $text.IndexOf('{')
    if ($brace -lt 0) { Write-Warning "  $settingsPath is not a JSON object; skipped."; return }

    if ($exists) {
        $bak = "$settingsPath.qrspi-$(Get-Date -Format yyyyMMdd-HHmmss).bak"
        Copy-Item -LiteralPath $settingsPath $bak
        Write-Host "  backup -> $bak" -ForegroundColor DarkGray
    }
    else { New-Item -ItemType Directory -Force (Split-Path $settingsPath) | Out-Null }

    $new = $text.Insert($brace + 1, "`n" + ($toInject -join "`n"))
    Set-Content -LiteralPath $settingsPath -Value $new -NoNewline -Encoding utf8
    Write-Host "  Patched. Reload the VS Code window (Developer: Reload Window)." -ForegroundColor Green
}

$dst = Join-Path $HOME '.copilot'
Write-Host "`nInstalling GitHub Copilot kit -> $dst" -ForegroundColor Cyan

# Self-heal: remove stale opsx/openspec Copilot files left by kit v0.1.0.
# These files were generated by the old opsx command surface and are no
# longer shipped. Delete them before copying so they do not persist in
# user scope after upgrading from v0.1.0.
$staleFiles = @(
    'prompts/opsx-propose.prompt.md',
    'prompts/opsx-explore.prompt.md',
    'prompts/opsx-apply.prompt.md',
    'prompts/opsx-archive.prompt.md',
    'prompts/opsx-sync.prompt.md',
    'instructions/openspec-propose.instructions.md',
    'instructions/openspec-explore.instructions.md',
    'instructions/openspec-apply-change.instructions.md'
)
foreach ($rel in $staleFiles) {
    $stale = Join-Path $dst $rel
    if (Test-Path $stale) {
        Remove-Item -Force $stale
        Write-Host ("  removed stale: {0}" -f $rel) -ForegroundColor DarkGray
    }
}

Copy-Tree (Join-Path $src 'copilot/agents')       (Join-Path $dst 'agents')       'agents'
Copy-Tree (Join-Path $src 'copilot/instructions') (Join-Path $dst 'instructions') 'instructions'
Copy-Tree (Join-Path $src 'copilot/prompts')      (Join-Path $dst 'prompts')      'prompts'
Write-Host "Copilot: VS Code only reads these once its chat.*FilesLocations point at ~/.copilot." -ForegroundColor DarkCyan
if ($SkipSettings) {
    Write-Host "  (-SkipSettings) add by hand to your user settings.json:" -ForegroundColor DarkCyan
    Write-Host '           "chat.promptFilesLocations":       { "~/.copilot/prompts": true },' -ForegroundColor Yellow
    Write-Host '           "chat.agentFilesLocations":        { "~/.copilot/agents": true },' -ForegroundColor Yellow
    Write-Host '           "chat.instructionsFilesLocations": { "~/.copilot/instructions": true }' -ForegroundColor Yellow
}
else {
    $settings = @(Get-VSCodeSettingsPaths | Where-Object { Test-Path (Split-Path $_) })
    if (-not $settings) {
        Write-Host "  No VS Code install detected. Add the chat.*FilesLocations keys by hand," -ForegroundColor DarkCyan
        Write-Host "  or re-run with the editor installed." -ForegroundColor DarkCyan
    }
    else {
        foreach ($s in $settings) { Add-CopilotSettings $s }
    }
}
Write-Host "Then reload the VS Code window and type / in Copilot Chat to see the qrspi prompts." -ForegroundColor DarkCyan

Write-Host "`nDone." -ForegroundColor Cyan
